---
Name: mymoduleroutes
Before:
  - 'mysite'
  - 'app'
After:
  - 'framework'
---
SilverStripe\Control\Director:
  rules:
    'admin/settings/bugsnag//$Action': 'Violet88\BugsnagModule\BugsnagSiteConfigExtension_Controller'
