<?php

namespace Violet88\BugsnagModule;

use SilverStripe\Control\HTTPRequest;
use SilverStripe\Control\HTTPResponse;
use SilverStripe\Core\Environment;
use SilverStripe\Dev\DevBuildController;

class DevBuildExtension extends DevBuildController
{

    private static $url_handlers = array(
        '' => 'build'
    );

    private static $allowed_actions = array(
        'build'
    );

    public function build($request): HTTPResponse
    {
        $bugsnag = new Bugsnag();
        if (Environment::getEnv('BUGSNAG_RELEASE_STAGE')) {
            $bugsnag->bugsnag->build();
        }
        return parent::build($request); // TODO: Change the autogenerated stub
    }

}